version: "3.9"

services:
  app_training_dev_container:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
       - ../task:/workspace:cached
       - ../../../bin-job-posting:/bin-job-posting
    command: /bin/sh -c "sleep infinity"