version: "3.9"

services:
  app_jupyter:
    build:
      context: .
    volumes:
      - ../../bin-job-posting:/tf/bin-job-posting
    ports:
      - "8888:8888"
      - "6006:6006"
    stdin_open: true
    tty: true